Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ParcelXpress.Models;
using System.Data;
using ParcelXpress.Helpers;
using ParcelXpress.Enums;

namespace ParcelXpress.Controllers
{
    [Authorize]
    public class DriverController : Controller
    {
        //
        // GET: /Driver/
        ParcelXpressConnection _db = new ParcelXpressConnection();

        public ActionResult DriverRequests()
        {

            var driverRequestList = from driver in _db.REQT_DRVR
                                    where driver.IsConverted == false
                                    orderby driver.DriverReqId
                                    select driver;

            return View(driverRequestList);
        }

        public ActionResult AllDrivers(string searchTerm = null)
        {
            var model = _db.DRVR_DATA
                .Where(r => (searchTerm == null || r.DriverName.StartsWith(searchTerm)) && r.IsDeleted != true)
                .OrderBy(r => r.DriverName);

            int newReqCount = _db.REQT_DRVR.Where(r => r.IsConverted == false).Count();
            ViewData["newRequestCount"] = newReqCount;

            if (Request.IsAjaxRequest())
            {
                return PartialView("_DriversTable", model);
            }
            return View(model);
        }

        public ActionResult DeleteDriverRequest(int id)
        {
            REQT_DRVR requestData = new REQT_DRVR();
            requestData = _db.REQT_DRVR.Find(id);
            if (requestData != null)
            {
                _db.Entry(requestData).State = EntityState.Deleted;
                _db.SaveChanges();

                TempData["toastMessage"] = "<script>toastr.success('Request has been successfully deleted.');</script>";
            }
            return RedirectToAction("DriverRequests");
        }

        public ActionResult RegisterDriver(int id)
        {
            REQT_DRVR requestData = new REQT_DRVR();
            requestData = _db.REQT_DRVR.Find(id);

            DRVR_DATA driverData = new DRVR_DATA()
            {
                DriverName = requestData.DriverName,
                LoginName = requestData.LoginName,
                Password = requestData.Password,
                GcmId = requestData.GcmId,
                SecurityQuestionId = requestData.SecurityQuestionId,
                SecurityAnswer = requestData.SecurityAnswer,
                IsActive = false,
                ContactNo = requestData.ContactNo
            };
            ViewData["requestId"] = id;

            return View(driverData);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult saveNewDriver(DRVR_DATA driver, int reqtId)
        {
            REQT_DRVR requestData = new REQT_DRVR();
            requestData = _db.REQT_DRVR.Find(reqtId);
            try
            {
                driver.CommissionRate = driver.CommissionRate == null ? 0.00M : driver.CommissionRate;
                if (ModelState.ContainsKey("CommissionRate"))
                    ModelState["CommissionRate"].Errors.Clear();
                if (ModelState.IsValid)
                {
                    driver.IsDeleted = false;
                    driver.CreatedOn = (DateTime.Now).ToUniversalTime();
                    _db.DRVR_DATA.Add(driver);

                    _db.Entry(requestData).State = EntityState.Modified;
                    requestData.IsConverted = true;
                    _db.SaveChanges();

                    TempData["toastMessage"] = "<script>toastr.success('Driver has been successfully saved into the system.');</script>";
                    GcmSender.SendToSingle(driver, "You are now registered into the system. You can use your Id password to login.", "register_success");
                    return RedirectToAction("AllDrivers");
                }
                else
                {
                    TempData["toastMessage"] = "<script>toastr.error('Driver data could not be saved.');</script>";
                }
            }
            catch (Exception ex)
            {
                TempData["toastMessage"] = "<script>toastr.error('An error occured while saving the driver.');</script>";
            }
            return RedirectToAction("RegisterDriver", new { id = reqtId });
        }

        public ActionResult EditDriver(int id)
        {
            DRVR_DATA driverData = _db.DRVR_DATA.Find(id);
            return View(driverData);
        }

        [HttpPost]
        public ActionResult editDriverInformation(DRVR_DATA driver)
        {
            try
            {
                driver.CommissionRate = driver.CommissionRate == null ? 0.00M : driver.CommissionRate;
                if (ModelState.ContainsKey("CommissionRate"))
                    ModelState["CommissionRate"].Errors.Clear();
                if (ModelState.IsValid)
                {
                    _db.Entry(driver).State = EntityState.Modified;
                    _db.SaveChanges();
                    TempData["toastMessage"] = "<script>toastr.success('Driver has been successfully updated in the system.');</script>";

                }
                else
                {
                    TempData["toastMessage"] = "<script>toastr.error('Driver data could not be updated.');</script>";
                }
            }
            catch (Exception ex)
            {
                TempData["toastMessage"] = "<script>toastr.error('An exception occured while trying to update the driver information.');</script>";
            }
            return RedirectToAction("AllDrivers");
        }

        [HttpPost]
        public ActionResult DeleteDriver(int DriverId)
        {
            try
            {
                var driver = _db.DRVR_DATA.Find(DriverId);
                driver.IsDeleted = true;
                _db.Entry(driver).State = EntityState.Modified;
                _db.SaveChanges();
                TempData["toastMessage"] = "<script>toastr.success('Driver has been successfully deleted from the system.');</script>";
            }
            catch (Exception ex)
            {
                TempData["toastMessage"] = "<script>toastr.error('There was an error while processing your request.');</script>";
            }
            return RedirectToAction("AllDrivers");
        }

        public ActionResult _ActiveDriversDashboard()
        {
            var model = _db.DRVR_DATA.Where(d => d.IsActive == true && d.IsDeleted != true).ToList();
            foreach (var item in model)
            {
                item.ActiveJobsCount = item.JOBS.Where(p => (p.JobStatus == StringEnum.GetStringValue(StatusCode.Assigned)) || (p.JobStatus == StringEnum.GetStringValue(StatusCode.PickedUp)) || (p.JobStatus == StringEnum.GetStringValue(StatusCode.DroppedOff))).Count();
                item.isTimeIn = item.DRVR_TIME_SHET.LastOrDefault(p => p.IsLoggedIn == true) != null;
                item.AdditionalInfo = item.DRVR_TIME_SHET.LastOrDefault(d => d.IsLoggedIn == true) != null ? TimezoneHelper.ConvertUTCtoLocal(item.DRVR_TIME_SHET.LastOrDefault(d => d.IsLoggedIn == true).LoginTime.Value).ToString("hh:mm tt") : "";
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("_ActiveDriversList", model);
            }
            return PartialView(model);
        }

        public ActionResult AcceptHourlyDriver(int driverId)
        {
            try
            {
                var driver = _db.DRVR_DATA.Find(driverId);
                if (driver.IsOnHourlyRate == false || !driver.HourlyRate.HasValue || driver.HourlyRate <= 0)
                {
                    throw new Exception("Hourly rate is not defined for selected driver");
                }
                DRVR_TIME_SHET timeSheet = new DRVR_TIME_SHET()
                {
                    DriverId = driver.DriverId,
                    HourlyRate = driver.HourlyRate,
                    IsLoggedIn = true,
                    LoginTime = DateTime.Now.ToUniversalTime(),
                    SettledInd = false
                };
                _db.DRVR_TIME_SHET.Add(timeSheet);
                _db.SaveChanges();
                TempData["toastMessage"] = "<script>toastr.success('Driver has been successfully accepted. Driver time recording has been started');</script>";
            }
            catch (Exception ex)
            {
                TempData["toastMessage"] = "<script>toastr.error('" + ex.Message + "');</script>";
            }
            return RedirectToAction("Dashboard", "Index");
        }

        public ActionResult LogoutHourlyDriver(int driverId)
        {
            try
            {
                var driverTimeSheet = _db.DRVR_TIME_SHET.Where(d => d.DriverId == driverId && d.IsLoggedIn == true);
                foreach (var item in driverTimeSheet)
                {
                    item.IsLoggedIn = false;
                    item.LogoutTime = DateTime.Now.ToUniversalTime();
                    TimeSpan hoursWorked = (item.LogoutTime - item.LoginTime).GetValueOrDefault(new TimeSpan());
                    item.AmountEarned = (decimal)(hoursWorked.TotalHours) * item.HourlyRate.GetValueOrDefault(0);
                    _db.Entry(item).State = EntityState.Modified;
                }
                _db.SaveChanges();
                TempData["toastMessage"] = "<script>toastr.success('Driver time recording has been stopped successfully.');</script>";

            }
            catch (Exception ex)
            {
                TempData["toastMessage"] = "<script>toastr.error('" + ex.Message + "');</script>";
            }
            return RedirectToAction("Dashboard", "Index");
        }
    }
}

Views/Driver/AllDrivers.cshtml
@model IEnumerable<DRVR_DATA>

@{
    ViewBag.Title = "AllDrivers";
}

<div class="container" style="margin-top:3%;">

    <div class="panel panel-default box box-danger">
        <div class="panel-heading">
            <h3>Drivers</h3>
        </div>

        <div class="panel-body">
            <div class="input-group col-lg-2 col-lg-offset-10 right" style="display:block;width:100%;">
                <a href="/Driver/DriverRequests" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-user"></span> Driver Requests <span class="badge">@ViewData["newRequestCount"]</span></a>
            </div>
            <div class="container-fluid box-body">
                <div class="row">
                    <div class="box-header">
                        <h4>Registered Drivers</h4>
                    </div>
                </div>

                <div class="row" style="margin-bottom:1%;">
                    <form method="get" action="@Url.Action("AllDrivers")" data-pxp-ajax="true" data-pxp-target="#registeredDrivers">
                        <div class="col-xs-7 col-sm-5 col-md-3">
                            <div class="input-group col-sm-12">
                                <input type="search" class="form-control" placeholder="Search&hellip;" name="searchTerm" />
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> </button>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>

                @Html.Partial("_DriversTable", Model)
            </div>
           
        </div>
    </div>
</div>
@Html.Raw(TempData["toastMessage"])

Views/Driver/DriverRequests.cshtml
@model IEnumerable<ParcelXpress.Models.REQT_DRVR>

@{
    ViewBag.Title = "New Driver";
}


@if (Model.Count() == 0)
{
    <div class="container">
        <div class="h4 text-danger">
            <h4>No new driver request found</h4>
        </div>
    </div>
}
else
{
    <div class="container">
        <div class="col-lg-10">
            <table class="table table-striped table-hover table-responsive" style="background-color:#f7f4d8">
                <caption class="h3 text-danger">Driver Requests</caption>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Login name</th>
                        <th>Contact Number</th>
                        <th></th>
                        <th></th>
                      
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="disabled">
                            <td>@item.DriverName</td>
                            <td>@item.LoginName</td>
                            <td>@item.ContactNo</td>
                            <td>@Html.ActionLink("View Details","RegisterDriver","Driver",new{id=@item.DriverReqId},new{@class="btn btn-primary"})</td>
                            <td>@Html.ActionLink("Delete", "DeleteDriverRequest", "Driver", new { id = @item.DriverReqId }, new { @class = "btn btn-danger" })</td>
                           
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

@Html.Raw(TempData["toastMessage"])

Views/Driver/EditDriver.cshtml
@model ParcelXpress.Models.DRVR_DATA

@{
    ViewBag.Title = "EditDriver";
}
<div class="container-fluid">
    <section class="content-header">
        <h2>Edit Driver</h2>
    </section>
    

    <div class="col-lg-9">
        <div class="box box-primary container-fluid">
            <div class="box-header">
                <h4 class="col-sm-8">Driver Details</h4>
                @using (Html.BeginForm("DeleteDriver", "Driver", null, FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.HiddenFor(m => m.DriverId);
                    <button type="submit" role="button" class="btn btn-danger col-sm-2" id="btnDelete" style="margin-top:1%; "><span class="glyphicon glyphicon-remove"></span> Delete Driver</button>
                }
            </div>
            @using (Html.BeginForm("editDriverInformation", "Driver", new { reqtId = ViewData["requestId"] }, FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="box-body">
                    @Html.Partial("_DriverDetails", Model, new ViewDataDictionary { { "isDisabled", "false" } })
                </div>

                <div class="box-footer">

                    <button class="btn btn-primary col-lg-2 col-sm-offset-3" type="submit" style="margin-bottom:2%;">Save</button>

                </div>
            }
        </div>
    </div>

</div>
@Html.Raw(TempData["toastMessage"])

Views/Driver/RegisterDriver.cshtml
@model ParcelXpress.Models.DRVR_DATA

@{
    ViewBag.Title = "RegisterDriver";
}
<div class="container-fluid">
    <section class="content-header">
        <h2>Register Driver</h2>
    </section>

    @using (Html.BeginForm("saveNewDriver", "Driver", new { reqtId = ViewData["requestId"] }, FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="col-lg-9">
            <div class="box box-primary container-fluid">
                <div class="box-header">
                    <h4>Driver Details</h4>
                </div>

                <div class="box-body">
                    @Html.Partial("_DriverDetails", Model, new ViewDataDictionary { { "isDisabled", "false" } })
                </div>

                <div class="box-footer">                 
                    <button class="btn btn-primary col-lg-2" type="submit" style="margin-bottom:2%;">Save</button>                  
                </div>
            </div>
        </div>
    }
</div>
@Html.Raw(TempData["toastMessage"])

Views/Driver/_ActiveDriversDashboard.cshtml
@model List<DRVR_DATA>
<div id="activeDriverRefresh">
    <div id="activeDriverGrid">
        <div class="container-fluid">
            <div class="panel panel-primary mdl-shadow--4dp">
                <div class="panel-heading panel-title">
                    <div class="mdl-card__title zero-margins">
                        <h5 style="color:white;" class="zero-margins">Active Drivers</h5>
                        <div class="mdl-layout-spacer"></div>
                        <a href="/Driver/_ActiveDriversDashboard" class="btn mdl-button--accent mdl-button--raised refreshDriverButton" data-pxp="true" data-pxp-target="#activeDriverGrid"><span class="glyphicon glyphicon-refresh"></span></a>
                    </div>

                </div>
                @Html.Partial("_ActiveDriversList", Model)
            </div>
        </div>
    </div>
</div>

Views/Driver/_ActiveDriversList.cshtml
@model List<DRVR_DATA>
<div id="activeDriversList">
    <div class="panel-body">
        <div class="row label-primary">
            <div class="col-sm-12" style="margin-top:5px;">
                <label class="control-label col-xs-8" style="color: #e9e5b6;">Auto Refresh</label>
                <div class="col-xs-1">
                    <input type="checkbox" id="autoRefreshActiveDrivers" />
                </div>
            </div>
        </div>
        @if (Model.Count <= 0)
            {
            <div class="container custom-list-withoutPager">
                <div class="text-danger">
                    <h6 class="col-sm-12">There are no active drivers</h6>
                </div>
            </div>
        }
        else
        {
            <div class="panel-body custom-list-withoutPager" id="activedriverlist">
                @foreach (var item in Model)
                {
                    <div class="row">
                        <div class="col-md-8">
                            <a href="/Jobs/DriverActiveJobs?driverId=@item.DriverId">
                                <div class="row" style="padding-top:-10px !important;">
                                    <h6 class="zero-margins">
                                        @item.DriverName
                                        <small style="font-size:0.8em !important; font-weight:bolder">@item.ContactNo</small>
                                    </h6>
                                </div>
                                <div class="row">
                                    <p style="color:#3d3c3c">@item.ActiveJobsCount Jobs</p>
                                </div>
                                @if (item.IsOnHourlyRate == true && item.isTimeIn == true)
                                {
                                    <div class="row">
                                        <p style="color:#3d3c3c"><b>Logged in since:</b> @item.AdditionalInfo</p>
                                    </div>
                                }

                            </a>
                        </div>
                        <div class="col-md-4">
                            @if (item.IsOnHourlyRate == true && item.isTimeIn == false)
                            {
                                <a class="btn btn-primary" href="/Driver/AcceptHourlyDriver?driverId=@item.DriverId">Accept</a>
                            }
                            else if (item.IsOnHourlyRate == true && item.isTimeIn == true)
                            {
                                <a class="btn btn-primary" href="/Driver/LogoutHourlyDriver?driverId=@item.DriverId">Logout</a>
                            }
                        </div>
                    </div>
                    <hr />
                }

            </div>
        }
    </div>
    <div class="panel-footer text-center">

    </div>
</div>

<script>
    var interval = null;
    $(document).on('ready', function () {
        $('#autoRefreshActiveDrivers').attr('checked', 'checked');
        interval = setInterval(updateDrivers, 10000);
    });
    function updateDrivers() {
        $.ajax({
            url: '/Driver/_ActiveDriversDashboard',
            success: function (data) {
                if ($('#autoRefreshActiveDrivers').is(":checked") == true) {
                    $('#activeDriversList').html(data);
                    $('#autoRefreshActiveDrivers').attr('checked', 'checked');
                }
            },
            error: function () {
                clearInterval(interval);
            }
        });
    }


    $('#autoRefreshActiveDrivers').on('click', function (e) {
        if ($(this).is(":checked") == true) {
            interval = setInterval(updateJobs, 10000);
        }
        else {
            clearInterval(interval);
        }
    });
</script>

Views/Driver/_DriverDetails.cshtml
@model ParcelXpress.Models.DRVR_DATA

@{
    var disabled = ViewData["isDisabled"];
    Model.IsDeleted = false;
}
<div class="row">
    <div class="col-md-6 form-group">
        <label class="control-label col-lg-4 ">On Hourly Wage</label>
        <div class="col-lg-1">
            @Html.CheckBoxFor(m => m.IsOnHourlyRate, new { @class = "form-control", @id = "hourlyDriverCheck" })
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6 form-group">
        <label class="control-label col-lg-3">Driver Name</label>
        <div class="col-lg-8">
            @Html.TextBoxFor(m => m.DriverName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.DriverName, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-lg-6 form-group">
        <label class="control-label col-lg-3">Login Name</label>
        <div class="col-lg-8">
            @Html.TextBoxFor(m => m.LoginName, new { @class = "form-control isDisabled" })
            @Html.ValidationMessageFor(m => m.LoginName, null, new { @class = "text-danger" })
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6 form-group">
        <label class="control-label col-lg-3">Contact No.</label>
        <div class="col-lg-8">
            @Html.TextBoxFor(m => m.ContactNo, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ContactNo, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-lg-6 form-group">
        <label class="control-label col-lg-3">GCM ID</label>
        <div class="col-lg-8">
            @Html.TextBoxFor(m => m.GcmId, new { @class = "form-control isDisabled" })      @*//Get controls from isDisabled Class and play in Javascript*@
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6 form-group">
        <label class="control-label col-lg-3">Commission %</label>
        <div class="col-lg-8">
            @Html.TextBoxFor(m => m.CommissionRate, new { @id = "txtCommissionRate" })
            @Html.ValidationMessageFor(m => m.CommissionRate, null, new { @class = "text-danger" })
        </div>
    </div>
    @*<div class="col-lg-6 form-group">
        <label class="control-label col-lg-3">Commission %</label>
        <div class="col-lg-8">
            @Html.TextBoxFor(m => m.CommissionRate, new { @id = "txtCommissionRate" })
            @Html.ValidationMessageFor(m => m.CommissionRate, null, new { @class = "text-danger" })
        </div>
    </div>*@
    <div class="col-lg-6 form-group">
        <label class="control-label col-lg-3">Hourly Rate</label>
        <div class="col-lg-8">
            @Html.TextBoxFor(m => m.HourlyRate)
            @Html.ValidationMessageFor(m => m.HourlyRate, null, new { @class = "text-danger" })
        </div>
    </div>
</div>
@Html.HiddenFor(m => m.Password)
@Html.HiddenFor(m => m.IsActive)
@Html.HiddenFor(m => m.DriverId)
@Html.HiddenFor(m => m.IsDeleted)
@Html.HiddenFor(m => m.CreatedOn)

Views/Driver/_DriversTable.cshtml
@model IEnumerable<DRVR_DATA>

<div class="row col-md-12" id="registeredDrivers">
    <table class="table table-bordered table-responsive table-hover">
        <thead>
            <tr>
                <th>Driver Name</th>
                <th>Contact Number</th>
                <th>Commission %</th>
                <th>Hourly rate</th>
                <th>Active now</th>
                <th>Last Logout</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.DriverName</td>
                    <td>@item.ContactNo</td>
                    <td>@item.CommissionRate</td>
                    <td>@item.HourlyRate</td>
                    <td><input type="checkbox" class="checkbox-inline" value="@item.IsActive" checked="@item.IsActive" disabled="disabled" /></td>
                    <td>@(item.LogoutTime!=null?TimezoneHelper.ConvertUTCtoLocal(item.LogoutTime.Value).ToString("dd-MMM-yyyy hh:mm tt"):"")</td>
                    <td>@Html.ActionLink("View Details", "EditDriver", "Driver", new { id = @item.DriverId }, new { @class = "btn btn-primary" })</td>
                </tr>
            }
        </tbody>
    </table>
</div>