Models/FAQ.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelXpress.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class FAQ
    {
        public int FaqId { get; set; }
        [Required]
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
    }
}

Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ParcelXpress.Models;
using PagedList;
using System.Data;


namespace ParcelXpress.Controllers
{
    [Authorize]
    public class FAQController : Controller
    {
        //
        // GET: /FAQ/
        ParcelXpressConnection _db = new ParcelXpressConnection();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowFAQS(int page = 1)
        {
            var model = _db.FAQS.OrderByDescending(f => f.Date).ToPagedList(page, 15);
            return View(model);
        }
        public ActionResult AddFaq()
        {
            return View();
        }
        public ActionResult EditFaq(int faqId)
        {
            var model = _db.FAQS.Find(faqId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult saveNewFaq(FAQ faq)
        {
            try
            {
                faq.Date = DateTime.Now.ToUniversalTime();
                if (ModelState.IsValid)
                {
                    
                    _db.FAQS.Add(faq);
                    _db.SaveChanges();
                    TempData["toastMessage"] = "<script>toastr.success('FAQ has been successfully saved into the system.');</script>";
                }
                else 
                {
                    TempData["toastMessage"] = "<script>toastr.error('FAQ could not be saved.');</script>"; 
                }
            }
            catch (Exception ex)
            {
                TempData["toastMessage"] = "<script>toastr.error('FAQ could not be saved.');</script>"; 
            }
            return RedirectToAction("ShowFAQS");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult saveEditFaq(FAQ faq)
        {
            try
            {
                faq.Date = DateTime.Now.ToUniversalTime();
                if (ModelState.IsValid)
                {
                    _db.Entry(faq).State = EntityState.Modified;
                    _db.SaveChanges();
                    TempData["toastMessage"] = "<script>toastr.success('FAQ has been successfully saved.');</script>";
                }
                else
                {
                    TempData["toastMessage"] = "<script>toastr.error('FAQ could not be saved.');</script>";
                }
            }
            catch (Exception ex)
            {
                TempData["toastMessage"] = "<script>toastr.error('FAQ could not be saved.');</script>";
            }
            return RedirectToAction("ShowFAQS");
        }

        public ActionResult DeleteFaq(int FaqId)
        {
            try
            {
                var data = _db.FAQS.Find(FaqId);
                if (data != null)
                {
                    _db.Entry(data).State = EntityState.Deleted;
                    _db.SaveChanges();
                    TempData["toastMessage"] = "<script>toastr.success('FAQ has been successfully deleted.');</script>";
                }
                else
                    throw new Exception();
            }
            catch (Exception ex)
            {
                TempData["toastMessage"] = "<script>toastr.error('FAQ could not be deleted.');</script>"; 
            }
            return RedirectToAction("ShowFAQS");
        }
    }
}

Views/FAQ/AddFaq.cshtml
@model FAQ
@{

}
<div class="container-fluid">
    <section class="content-header">
        <h2>Add New FAQ</h2>
    </section>

    @using (Html.BeginForm("saveNewFaq", "FAQ", null, FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="col-lg-10">
            <div class="box box-primary container-fluid">
                <div class="box-header">
                    <h4 class="col-lg-8">FAQ Details</h4>

                </div>
                <div class="box-body">
                    @Html.Partial("_FAQDetails", Model)
                </div>

                <div class="box-footer">
                    <button class="btn btn-success col-lg-3 col-lg-offset-1" type="submit" style="margin-bottom:2%;" >Save Changes</button>
                </div>
            </div>
        </div>
    }
</div>
@Html.Raw(TempData["toastMessage"])

Views/FAQ/EditFaq.cshtml
@model FAQ
@{
    ViewBag.Title = "EditFaq";
}
<div class="container-fluid">
    <section class="content-header">
        <h2>Edit FAQ</h2>
    </section>

    @using (Html.BeginForm("saveEditFaq", "FAQ", null, FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="col-lg-10">
            <div class="box box-primary container-fluid">
                <div class="box-header">
                    <h4 class="col-lg-8">FAQ Details</h4>

                </div>
                <div class="box-body">
                    @Html.Partial("_FAQDetails", Model)
                    @Html.HiddenFor(m => m.FaqId)
                </div>

                <div class="box-footer">
                    <button class="btn btn-success col-lg-3 col-lg-offset-1" type="submit" style="margin-bottom:2%;">Save Changes</button>
                </div>
            </div>
        </div>
    }
</div>
@Html.Raw(TempData["toastMessage"])

Views/FAQ/ShowFAQS.cshtml
@model IPagedList<FAQ>

<section class="content-header container-fluid">
    <div class="col-lg-10 col-md-10"><h3>FAQs</h3></div>
    <div class="col-lg-2 col-md-2" style="padding-top:2%;"><a href="/FAQ/AddFaq" class="btn btn-primary"><span class="glyphicon glyphicon-plus"> Add New</span></a></div>
</section>

@if (Model.Count <= 0)
{
    <br />
    <div class="row">
        <div class="container">
            <div class="h4 text-danger">
                <h4>There were no FAQs found, Click Add to create one.</h4>
            </div>
        </div>
    </div>
}
else
{

    <div class="container-fluid">
        <div class="panel panel-primary container-fluid">
            <div class="panel-body" id="faqList">
                @foreach (var item in Model)
                {
                    <hr />
                    @Html.Partial("_FaqListItem", item)
                }

            </div>
            <div class="panel-footer text-center">
                <div class="pagedList" data-pxp-target="#faqList">
                    @Html.PagedListPager(Model, page => Url.Action("ShowFAQS", new { page }), PagedListRenderOptions.MinimalWithItemCountText)
                </div>
            </div>
        </div>
    </div>
}
@Html.Raw(TempData["toastMessage"])

Views/FAQ/_FAQDetails.cshtml
@model FAQ
          
<div class="row">
    <div class="form-group">
        <label class="control-label col-lg-3">Title</label>
        <div class="col-lg-8">
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Title, null, new { @class = "text-danger" })
        </div>
    </div>
</div>
<div class="row">
    <div class="form-group">
        <label class="control-label col-lg-3">Description</label>
        <div class="col-lg-8">
            @Html.TextAreaFor(m => m.Description, new { @class = "form-control",@placeholder="Optional",@style="height:250px!important;" })
            @Html.ValidationMessageFor(m => m.Description, null, new { @class = "text-danger" })
        </div>
    </div>
</div>

Views/FAQ/_FaqListItem.cshtml
@model FAQ
@{

}

<div class="row">
    <div class="col-md-10">
        <div class="row">
            <h4 class="zero-margins">
                <b>@Model.Title</b>&nbsp;&nbsp;
                <b><small style="font-size:0.8em !important; font-weight:bolder">@TimezoneHelper.ConvertUTCtoLocal(Model.Date).ToString("dd-MMM-yyyy hh:mm tt")</small></b>
            </h4>
        </div>
        <div class="row">
            @Model.Description
        </div>
    </div>
    <div class="col-md-1">
        <a href="/FAQ/EditFaq?faqId=@Model.FaqId" class="btn btn-primary"><span class="glyphicon glyphicon-edit"> Edit</span></a>
    </div>
    <div class="col-md-1">

        @using (Html.BeginForm("DeleteFaq", "FAQ", null, FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.HiddenFor(m => m.FaqId);
            <button type="submit" role="button" class="btn btn-danger" id="btnDelete"><span class="glyphicon glyphicon-remove"></span> Delete</button>
        }
    </div>
</div>